server:
  port: 8080

spring:
  datasource:
#    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test_db;DATABASE_TO_UPPER=false;MODE=MYSQL;DB_CLOSE_ON_EXIT=FALSE;
#    username: sa
#    password: sa
  h2:
    console:
      enabled: true
#  jpa:
#    hibernate:
#      ddl-auto: update